"""initial migration

Revision ID: 9b043473e2e7
Revises:
Create Date: 2025-12-04 11:33:35.824650

"""
import os
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b043473e2e7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Determine schema based on environment
# Reference: https://alembic.sqlalchemy.org/en/latest/cookbook.html
SCHEMA = 'app' if os.getenv('ENVIRONMENT') == 'production' else None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schema if needed (PostgreSQL only)
    if SCHEMA:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS {SCHEMA}')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    op.create_index(op.f('ix_heroes_level'), 'heroes', ['level'], unique=False, schema=SCHEMA)
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=False, schema=SCHEMA)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('YOUNG', 'OLD', name='usertype', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema=SCHEMA)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False, schema=SCHEMA)
    op.create_index(op.f('ix_users_type'), 'users', ['type'], unique=False, schema=SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_type'), table_name='users', schema=SCHEMA)
    op.drop_index(op.f('ix_users_name'), table_name='users', schema=SCHEMA)
    op.drop_index(op.f('ix_users_email'), table_name='users', schema=SCHEMA)
    op.drop_table('users', schema=SCHEMA)
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes', schema=SCHEMA)
    op.drop_index(op.f('ix_heroes_level'), table_name='heroes', schema=SCHEMA)
    op.drop_table('heroes', schema=SCHEMA)
    # ### end Alembic commands ###
