apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: goormthon-5
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  POSTGRES_DB: wadeulwadeul_db
